### ISSUE TITLE
Adding default Tag "Homebridge.Skip"

### ISSUE THREAD

**Issue by joergs-git** [timauton/Hue#1]
It makes sense adding automatically adding a default-tag "`Homebridge.Skip`" during virtual-devices creation - (for the sake of homebridge-zway-users.)
Since PhilipsHueBridge is anyway Homekit-enabled and delivering it's devices as Homekit-Devices already. So zway shouldn't need to do this as it doubles/triples the total amount of devices unneccessarily. (In my case I have suddenly more than 100 accessories delivered to homebridge-zway which breaks it completely).

So I simply added the following after each of your 3 device-creation functions:

[            }
        },
        moduleId: this.id
    });
	**vDev.addTag("Homebridge.Skip");**
};
](url)

**Comment by timauton** [comment]
Nice idea. As not everyone uses Homebridge and might not want the tags cluttering things up I've added it as an option in the development version.
