### ISSUE TITLE
New setting: Create color devices yes/no

### ISSUE THREAD

**Issue by joergs-git** [timauton/Hue#2]
Works really good so far after quickly doing some first tests.
But now, that Hue-devices are implemented and working properly, for me it doesn't make much sense having the color devices at all.
Specially, because it's much faster by simply using the iphone hue-app to pre-define colors and only use the hue-values to define them within scenes within zway. Additionally I would automatically get rid of around 18 virtual color-devicesm because I'd only use the Hue values from that moment on.
However,as not everyone might want to do this like I found most convenient it's probably worth simply adding another setting e.g. "Create rgb-color devices: yes/no". or so...

**Comment by timauton** [comment]
I've added options for creating colour devices to the dev branch. You can  now pick whether to create Hue/Sat controls, an XY colour picker, or both.
