### ISSUE TITLE
All devices disappear after reboot

### ISSUE THREAD

**Issue by mar-ops** [timauton/Hue#8]
The app works great, but after a reboot all the devices are gone. If I open the settings of the Philips Hue app and click on "save" the devices come all back.

Am I missing something or is there an error somewhere? All the devices should be always added again after a reboot.

**Comment by ghost** [comment]
Same here on z-way 3.0.6

**Comment by timauton** [comment]
I'm afraid I don't run ZWay any more so I'm afraid I'm unable to suggest any fixes.

I'm going to archive the repo (which I should have done a while ago - apologies!).
